; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG254033 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG254034 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG254035 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG254370 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG254371 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG254372 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG254800 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG254801 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG254802 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG248860 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG248861 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG248862 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG251866 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG251867 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG251868 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG252203 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG252204 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG252205 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG252540 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG252541 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG252542 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Dialog@@3Uqt_meta_stringdata_Dialog_t@@B DD 0ffffffffH ; qt_meta_stringdata_Dialog
	DD	06H
	DD	00H
	ORG $+4
	DQ	00000000000000c0H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	00000000000000afH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000a9H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000092H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000088H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000007dH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000070H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000063H
	DB	044H
	DB	069H
	DB	061H
	DB	06cH
	DB	06fH
	DB	067H
	DB	00H
	DB	063H
	DB	065H
	DB	06cH
	DB	06cH
	DB	044H
	DB	06fH
	DB	075H
	DB	062H
	DB	06cH
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	044H
	DB	065H
	DB	06cH
	DB	065H
	DB	074H
	DB	065H
	DB	041H
	DB	063H
	DB	065H
	DB	046H
	DB	075H
	DB	06eH
	DB	063H
	DB	00H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	053H
	DB	074H
	DB	061H
	DB	074H
	DB	075H
	DB	073H
	DB	00H
	DB	043H
	DB	06cH
	DB	065H
	DB	061H
	DB	06eH
	DB	054H
	DB	061H
	DB	062H
	DB	06cH
	DB	065H
	DB	00H
	DB	050H
	DB	072H
	DB	069H
	DB	06eH
	DB	074H
	DB	054H
	DB	061H
	DB	062H
	DB	06cH
	DB	065H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	052H
	DB	065H
	DB	061H
	DB	064H
	DB	046H
	DB	069H
	DB	06cH
	DB	065H
	DB	04eH
	DB	061H
	DB	06dH
	DB	065H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+5
	ORG $+8
?qt_meta_data_Dialog@@3QBIB DD 08H			; qt_meta_data_Dialog
	DD	00H
	DD	00H
	DD	00H
	DD	06H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	02cH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	02dH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	02eH
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	02fH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	030H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	031H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG253359 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG253360 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG253361 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG253696 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG253697 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG253698 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ	; Dialog::metaObject
PUBLIC	?qt_metacast@Dialog@@UEAAPEAXPEBD@Z		; Dialog::qt_metacast
PUBLIC	?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Dialog::qt_metacall
PUBLIC	?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Dialog::qt_static_metacall
PUBLIC	?staticMetaObject@Dialog@@2UQMetaObject@@B	; Dialog::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?cellDoubleClicked@Dialog@@AEAAXXZ:PROC		; Dialog::cellDoubleClicked
EXTRN	?DeleteAceFunc@Dialog@@AEAAXXZ:PROC		; Dialog::DeleteAceFunc
EXTRN	?ChangeStatus@Dialog@@AEAAXXZ:PROC		; Dialog::ChangeStatus
EXTRN	?CleanTable@Dialog@@AEAAXXZ:PROC		; Dialog::CleanTable
EXTRN	?PrintTable@Dialog@@AEAAXXZ:PROC		; Dialog::PrintTable
EXTRN	?on_ReadFileName_clicked@Dialog@@AEAAXXZ:PROC	; Dialog::on_ReadFileName_clicked
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@Dialog@@2UQMetaObject@@B DB 030H DUP (?) ; Dialog::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Dialog@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Dialog@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN14
	DD	imagerel $LN14+180
	DD	imagerel $unwind$?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Dialog@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Dialog@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Dialog@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Dialog@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Dialog@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Dialog@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Dialog::staticMetaObject'', COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 102
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B, rax
; Line 103
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Dialog@@3Uqt_meta_stringdata_Dialog_t@@B
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B+8, rax
; Line 104
	lea	rax, OFFSET FLAT:?qt_meta_data_Dialog@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B+16, rax
; Line 105
	lea	rax, OFFSET FLAT:?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Dialog::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B+24, rax
; Line 106
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B+32, 0
; Line 107
	mov	QWORD PTR ?staticMetaObject@Dialog@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Dialog@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Dialog::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Dialog::qt_static_metacall
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 84
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 85
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 86
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 88
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 5
	ja	SHORT $LN11@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN13@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 89
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?cellDoubleClicked@Dialog@@AEAAXXZ	; Dialog::cellDoubleClicked
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 90
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?DeleteAceFunc@Dialog@@AEAAXXZ		; Dialog::DeleteAceFunc
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 91
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?ChangeStatus@Dialog@@AEAAXXZ		; Dialog::ChangeStatus
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 92
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?CleanTable@Dialog@@AEAAXXZ		; Dialog::CleanTable
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 93
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?PrintTable@Dialog@@AEAAXXZ		; Dialog::PrintTable
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 94
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_ReadFileName_clicked@Dialog@@AEAAXXZ ; Dialog::on_ReadFileName_clicked
$LN11@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 99
	add	rsp, 56					; 00000038H
	ret	0
	npad	2
$LN13@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Dialog::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Dialog::qt_metacall
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 125
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 126
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 127
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 129
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 130
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN5@qt_metacal
; Line 131
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@Dialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Dialog::qt_static_metacall
$LN5@qt_metacal:
; Line 132
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 133
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 134
	cmp	DWORD PTR _id$[rsp], 6
	jge	SHORT $LN7@qt_metacal
; Line 135
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 136
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 6
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 138
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 139
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Dialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Dialog::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Dialog@@UEAAPEAXPEBD@Z PROC		; Dialog::qt_metacast
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 117
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 118
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 119
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Dialog@@3Uqt_meta_stringdata_Dialog_t@@B+192
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 120
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 121
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 122
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Dialog@@UEAAPEAXPEBD@Z ENDP		; Dialog::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ PROC	; Dialog::metaObject
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 112
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 113
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Dialog@@2UQMetaObject@@B ; Dialog::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 114
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Dialog@@UEBAPEBUQMetaObject@@XZ ENDP	; Dialog::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.13.1\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 142
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_dialog.cpp
; Line 142
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
