; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG246110 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG246111 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246112 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG246447 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG246448 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246449 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG246784 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG246785 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG246786 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG247603 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG247604 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247605 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_Integrity@@3Uqt_meta_stringdata_Integrity_t@@B DD 0ffffffffH ; qt_meta_stringdata_Integrity
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000003aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000002cH
	DB	049H
	DB	06eH
	DB	074H
	DB	065H
	DB	067H
	DB	072H
	DB	069H
	DB	074H
	DB	079H
	DB	00H
	DB	073H
	DB	06cH
	DB	06fH
	DB	074H
	DB	054H
	DB	069H
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	00H
	ORG $+3
?qt_meta_data_Integrity@@3QBIB DD 08H			; qt_meta_data_Integrity
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	08H
	DD	02bH
	DD	00H
	ORG $+4
$SG247940 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+4
$SG247941 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG247942 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG248277 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG248278 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG248279 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG243207 DB	'c:\qt\5.13.1\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG243208 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG243209 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ	; Integrity::metaObject
PUBLIC	?qt_metacast@Integrity@@UEAAPEAXPEBD@Z		; Integrity::qt_metacast
PUBLIC	?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Integrity::qt_metacall
PUBLIC	?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Integrity::qt_static_metacall
PUBLIC	?staticMetaObject@Integrity@@2UQMetaObject@@B	; Integrity::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?slotTimer@Integrity@@AEAAXXZ:PROC		; Integrity::slotTimer
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Integrity@@2UQMetaObject@@B DB 030H DUP (?) ; Integrity::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Integrity@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Integrity@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+72
	DD	imagerel $unwind$?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Integrity@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Integrity@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Integrity@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Integrity@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Integrity@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Integrity@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Integrity::staticMetaObject'', COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 80
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B, rax
; Line 81
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Integrity@@3Uqt_meta_stringdata_Integrity_t@@B
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B+8, rax
; Line 82
	lea	rax, OFFSET FLAT:?qt_meta_data_Integrity@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B+16, rax
; Line 83
	lea	rax, OFFSET FLAT:?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Integrity::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B+24, rax
; Line 84
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B+32, 0
; Line 85
	mov	QWORD PTR ?staticMetaObject@Integrity@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Integrity@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Integrity::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Integrity::qt_static_metacall
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 67
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 68
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 69
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 71
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 72
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?slotTimer@Integrity@@AEAAXXZ		; Integrity::slotTimer
$LN6@qt_static_:
$LN4@qt_static_:
; Line 77
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Integrity::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Integrity::qt_metacall
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 103
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 104
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 105
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 106
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 107
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 108
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 109
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@Integrity@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Integrity::qt_static_metacall
$LN5@qt_metacal:
; Line 110
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 111
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 112
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 113
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 114
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 116
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 117
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Integrity@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Integrity::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Integrity@@UEAAPEAXPEBD@Z PROC		; Integrity::qt_metacast
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 95
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 96
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 97
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Integrity@@3Uqt_meta_stringdata_Integrity_t@@B+72
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 98
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 99
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 100
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Integrity@@UEAAPEAXPEBD@Z ENDP		; Integrity::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ PROC	; Integrity::metaObject
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 90
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 91
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Integrity@@2UQMetaObject@@B ; Integrity::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 92
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Integrity@@UEBAPEBUQMetaObject@@XZ ENDP	; Integrity::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.13.1\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 120
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\user\desktop\mbks_1\mbks_1\debug\moc_integrity.cpp
; Line 120
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
